services:
  # ==============
  # Application
  # ==============

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    container_name: bookmark_saver_api
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    container_name: bookmark_saver_web
    environment:
      NODE_ENV: production
    depends_on:
      - api
    ports:
      - "80:80"

  database:
    image: postgres:16
    container_name: bookmark_saver_database
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - database_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  database_data:
