include:
  - ./docker-compose.base.yml

services:
  app:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    container_name: bookmark_saver_app
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"

  # web:
  #   build:
  #     context: ./web
  #     dockerfile: Dockerfile.prod
  #   container_name: bookmark_saver_web
  #   depends_on:
  #     - app
  #   ports:
  #     - "80:80"

  postgres:
    image: postgres:16
    container_name: bookmark_saver_db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
