services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    command: start
    # command: start --import-realm
    container_name: bookmark_saver_keycloak
    depends_on:
      keycloak-db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/${KEYCLOAK_DATABASE_NAME}
      KC_DB_USERNAME: ${KEYCLOAK_DATABASE_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DATABASE_PASSWORD}
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME}
      KC_HEALTH_ENABLED: "true"
      KC_HTTP_ENABLED: "true" # remove if you terminate TLS directly on keycloak
      # KC_PROXY_HEADERS: xforwarded # reverse proxy/nginx
    healthcheck:
      test: [ "CMD-SHELL", "curl -sf http://localhost:9000/health/ready || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 6
      start_period: 60s
    ports:
      - "8180:8080"
    # volumes:
    #   - ./keycloak.example.json:/opt/keycloak/data/import/keycloak.json

  keycloak-db:
    image: postgres:16
    container_name: bookmark_saver_keycloak_db
    environment:
      POSTGRES_USER: ${KEYCLOAK_DATABASE_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DATABASE_PASSWORD}
      POSTGRES_DB: ${KEYCLOAK_DATABASE_NAME}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${KEYCLOAK_DATABASE_USER} -d
            ${KEYCLOAK_DATABASE_NAME}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data

volumes:
  keycloak_postgres_data:
